"""Add new table and columns

Revision ID: 4ffdef42affe
Revises: 565a2430096e
Create Date: 2024-01-12 20:39:47.950681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffdef42affe'
down_revision: Union[str, None] = '565a2430096e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirm_account_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_confirm_account_tokens_id'), 'confirm_account_tokens', ['id'], unique=True, schema='user_schema')
    op.add_column('users', sa.Column('confirmed_account', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_account')
    op.drop_index(op.f('ix_user_schema_confirm_account_tokens_id'), table_name='confirm_account_tokens', schema='user_schema')
    op.drop_table('confirm_account_tokens', schema='user_schema')
    # ### end Alembic commands ###
