"""empty message

Revision ID: 565a2430096e
Revises: 
Create Date: 2023-12-28 23:35:38.008189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565a2430096e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_users_id'), 'users', ['id'], unique=True, schema='user_schema')
    op.create_index(op.f('ix_user_schema_users_name'), 'users', ['name'], unique=False, schema='user_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_schema_users_name'), table_name='users', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_users_id'), table_name='users', schema='user_schema')
    op.drop_table('users', schema='user_schema')
    # ### end Alembic commands ###
